In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pyam
import pandas as pd
from pandas_indexing import *

from ikea_pathways.data_check import *
import data_shepherd as ds

In [3]:
def elec(tech=None):
    if not tech is None:
        return f'Secondary Energy|Electricity|{tech}'
    else:
        return 'Secondary Energy|Electricity'

In [4]:
REMIND_RMAP = ds.utils.RegionMapping.from_model('REMIND_2.1')
REMIND_RMAP

RegionMapping(model_name='REMIND_2.1', iso_to_region=ISO
ABW    LAM
AFG    OAS
AGO    SSA
AIA    LAM
ALA    EUR
      ...
WSM    OAS
YEM    MEA
ZAF    SSA
ZMB    SSA
ZWE    SSA
Name: REMIND_2.1.REGION, Length: 246, dtype: object, region_names={'LAM': 'Latin America and the Caribbean', 'OAS': 'Other Asia', 'SSA': 'Sub-Saharan Africa', 'EUR': 'EU28', 'NEU': 'Europe (non-EU28)', 'MEA': 'Middle East and North Africa', 'REF': 'Russia', 'CAZ': 'Canada, Australia and New Zealand', 'CHA': 'China', 'IND': 'India', 'JPN': 'Japan', 'USA': 'USA'})

In [5]:
IKEA_ISOS = ["DEU","POL","BRA","MEX","KEN","MAR","MOZ",#"EU27",
             "NGA","SEN","ZAF","USA","NAM","DZA","TUR","SAU",
             "ARE","BGD","IND","IDN","PAK","VNM","GBR","AUS","CHN","JPN"]

IKEA_ISOS.sort()

# Load data

In [6]:
BOX_MOUNT_PATH = Path("~/Library/CloudStorage/Box-Box").expanduser()
if not BOX_MOUNT_PATH.is_dir():
    BOX_MOUNT_PATH = Path("~/Box").expanduser()

In [7]:
DSCALE_PATH = (
    "Climate Policy Team/"
    "02 - Projects/"
    "IKEA NDC 1.5° Pathways 23-25 - phase II/"
    "2 - Work Packages/"
    "WP2 - National 1.5°C Pathways/"
    "Downscaling/"
    "DSCALE"
)

DSCALE_PATH: os.PathLike = BOX_MOUNT_PATH / DSCALE_PATH

In [9]:
dscale_results = pyam.IamDataFrame(DSCALE_PATH /  'outputs/results_20260113/5_Explorer_and_New_Variables/REMIND-MAgPIE 3.3-4.8_REMIND_2025_2026_01_13_2022_harmo_step5e_None.csv')

pyam - INFO: Running in a notebook, setting up a basic logging at level INFO
pyam.core - INFO: Reading file /Users/marie-charlottegeffray/Library/CloudStorage/Box-Box/Climate Policy Team/02 - Projects/IKEA NDC 1.5° Pathways 23-25 - phase II/2 - Work Packages/WP2 - National 1.5°C Pathways/Downscaling/DSCALE/outputs/results_20260113/5_Explorer_and_New_Variables/REMIND-MAgPIE 3.3-4.8_REMIND_2025_2026_01_13_2022_harmo_step5e_None.csv

In [23]:
dscale_results.filter(variable = "*Trans*Liquids|Coal*")

<class 'pyam.core.IamDataFrame'>
Index:
 * model    : REMIND-MAgPIE 3.3-4.8 (1)
 * scenario : NPE-convEarly, NPE-convLate, NPE-core, NPE-demandStandard (4)
Timeseries data coordinates:
   region   : ABW, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, AZE, ... ZWE (193)
   variable : Final Energy|Transportation|Liquids|Coal (1)
   unit     : EJ/yr (1)
   year     : 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, ... 2100 (19)
Meta indicators:
   exclude (bool) False (1)

# Perform standard NPE data checks

In [10]:
class config:
    data_check_path : os.PathLike = DSCALE_PATH / "data_checks"

In [11]:
siamese_data_check(dscale_results.filter(region=IKEA_ISOS), config)

Coal
Gas
Oil
Biomass

/Users/marie-charlottegeffray/Documents/Repos/projects/1o5_pathways/src/ikea_pathways/data_check.py:399: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure()

Siamese check completed.

# Available variable in REMIND vs in NGFS

In [44]:
ngfs_results = pyam.IamDataFrame('../results/Archives_2025/5_Explorer_and_New_Variables/MESSAGEix-GLOBIOM 2.0-M-R12-NGFS_NGFS_2024_for_training_2026_01_07_2022_harmo_step5e_None.csv')

pyam.core - INFO: Reading file ../results/Archives_2025/5_Explorer_and_New_Variables/MESSAGEix-GLOBIOM 2.0-M-R12-NGFS_NGFS_2024_for_training_2026_01_07_2022_harmo_step5e_None.csv

In [45]:
ngfs_var = ngfs_results.filter(region = "DEU").variable
ngfs_var.sort()

In [46]:
dscale_var = dscale_results.filter(region = "DEU").variable
dscale_var.sort()

In [47]:
set(dscale_var).difference(set(ngfs_var))

{'Emissions|CO2|Energy|Supply|Electricity|Oil',
 'Final Energy|Residential and Commercial|Gases|Biomass',
 'Final Energy|Residential and Commercial|Gases|Natural Gas',
 'Final Energy|Residential and Commercial|Liquids|Biomass',
 'Final Energy|Transportation|Liquids|Coal',
 'Price|Carbon|Demand|Industry',
 'Price|Carbon|Demand|Residential and Commercial',
 'Price|Carbon|Demand|Transportation',
 'Price|Carbon|Supply',
 'Price|Final Energy|Industry|Electricity',
 'Price|Final Energy|Industry|Gases',
 'Price|Final Energy|Industry|Gases|Bioenergy',
 'Price|Final Energy|Industry|Gases|Fossil',
 'Price|Final Energy|Industry|Hydrogen',
 'Price|Final Energy|Industry|Liquids',
 'Price|Final Energy|Industry|Liquids|Bioenergy',
 'Price|Final Energy|Industry|Liquids|Fossil synfuel',
 'Price|Final Energy|Industry|Solids|Biomass',
 'Price|Final Energy|Industry|Solids|Coal',
 'Price|Final Energy|Residential and Commercial|Residential|Electricity',
 'Price|Final Energy|Residential and Commercial|Residential|Electricity|Index',
 'Price|Final Energy|Residential and Commercial|Residential|Gases|Natural Gas',
 'Price|Final Energy|Residential and Commercial|Residential|Gases|Natural Gas|Index',
 'Price|Final Energy|Residential and Commercial|Residential|Liquids|Biomass',
 'Price|Final Energy|Residential and Commercial|Residential|Liquids|Biomass|Index',
 'Price|Final Energy|Residential and Commercial|Residential|Liquids|Oil',
 'Price|Final Energy|Residential and Commercial|Residential|Liquids|Oil|Index',
 'Price|Final Energy|Residential and Commercial|Residential|Solids|Biomass',
 'Price|Final Energy|Residential and Commercial|Residential|Solids|Biomass|Index',
 'Price|Final Energy|Residential and Commercial|Residential|Solids|Coal',
 'Price|Final Energy|Residential and Commercial|Residential|Solids|Coal|Index',
 'Price|Final Energy|Transportation|Electricity',
 'Price|Final Energy|Transportation|Gases',
 'Price|Final Energy|Transportation|Hydrogen',
 'Price|Final Energy|Transportation|Liquids',
 'Price|Final Energy|Transportation|Liquids|Fossil synfuel',
 'Price|Primary Energy|Biomass|Index',
 'Price|Primary Energy|Coal|Index',
 'Price|Primary Energy|Gas|Index',
 'Price|Primary Energy|Oil|Index',
 'Price|Secondary Energy|Electricity|Index',
 'Price|Secondary Energy|Gases|Natural Gas',
 'Price|Secondary Energy|Gases|Natural Gas|Index',
 'Price|Secondary Energy|Hydrogen|Index',
 'Price|Secondary Energy|Liquids|Biomass|Index',
 'Price|Secondary Energy|Liquids|Index',
 'Price|Secondary Energy|Liquids|Oil|Index',
 'Price|Secondary Energy|Solids|Coal',
 'Price|Secondary Energy|Solids|Coal|Index',
 'Statistical Difference|Primary Energy|Fossil|w/ CCS'}

In [49]:
mask = (dscale_results.subtract(
    "Final Energy|Transportation|Liquids",
    "Final Energy|Transportation|Liquids|Oil", 
    "Final Energy|Transportation|Liquids - Oil"
).timeseries() < 0 ).sum(axis=1)

In [50]:
rows_above_zero = mask.loc[mask > 0]

In [51]:
rows_above_zero.index.unique("region")

Index(['AGO', 'ARE', 'BEN', 'BFA', 'BGD', 'BOL', 'BRN', 'BWA', 'CHL', 'CIV',
       'CMR', 'COD', 'COG', 'CRI', 'CUB', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI',
       'ETH', 'GAB', 'GHA', 'GNQ', 'GTM', 'GUY', 'HND', 'IDN', 'IRN', 'IRQ',
       'ISR', 'JAM', 'KEN', 'KHM', 'KOR', 'KWT', 'LAO', 'LBY', 'MAR', 'MDG',
       'MEX', 'MLI', 'MMR', 'MNG', 'MOZ', 'MRT', 'MUS', 'MYS', 'NAM', 'NER',
       'NGA', 'NIC', 'NPL', 'OMN', 'PAK', 'PAN', 'PHL', 'PRK', 'RWA', 'SAU',
       'SEN', 'SGP', 'SLV', 'SUR', 'SWZ', 'SYR', 'TCD', 'TGO', 'THA', 'TTO',
       'TZA', 'UGA', 'URY', 'VEN', 'VNM', 'ZAF', 'ZMB', 'ZWE'],
      dtype='object', name='region')

In [52]:
ngfs_results.filter(variable = "*Tran*").variable

['Final Energy|Transportation',
 'Final Energy|Transportation|Electricity',
 'Final Energy|Transportation|Gases',
 'Final Energy|Transportation|Hydrogen',
 'Final Energy|Transportation|Liquids',
 'Final Energy|Transportation|Liquids|Oil',
 'Revenue|Government|Tax|Carbon|Demand|Transportation']

In [3]:
ngfs_input = pyam.IamDataFrame("/Users/marie-charlottegeffray/Documents/Repos/projects/DSCALE/input_data/NGFS_2024_for_training/snapshot_v1/Book1.csv")

pyam - INFO: Running in a notebook, setting up a basic logging at level INFO
pyam.core - INFO: Reading file /Users/marie-charlottegeffray/Documents/Repos/projects/DSCALE/input_data/NGFS_2024_for_training/snapshot_v1/Book1.csv

In [7]:
ngfs_input.filter(variable = "Secondary Energy|Electricity|Coal").timeseries()

,,,,,2005,2010,2015,2020,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
model,scenario,region,variable,unit,,,,,,,,,,,,,,,,,,,,
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS,h_cpol,MESSAGEix-GLOBIOM 2.0-M-R12-NGFS|Western Europe,Secondary Energy|Electricity|Coal,EJ/yr,2.743527,2.356878,2.420729,1.217071,0.910143,0.547963,0.405047,0.330647,0.455718,0.42882,0.07132,0.019662,0.009831,0.0,0.004599,0.009198,0.017044,0.024889,0.024085,0.02328

In [16]:
ngfs_results.aggregate_region("Secondary Energy|Electricity|Coal").timeseries()

,,,,,2010,2015,2020,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
model,scenario,region,variable,unit,,,,,,,,,,,,,,,,,,,
MESSAGEix-GLOBIOM 2.0-M-R12-NGFS,h_cpol,World,Secondary Energy|Electricity|Coal,EJ/yr,2.3674,2.3863,1.1414,0.9879,0.5878,0.4251,0.3405,0.4627,0.4291,0.0713,0.0198,0.0097,0.0,0.0044,0.0092,0.0169,0.025,0.024,0.0232

# Regional consistency checks

In [53]:

# Regroup all the rescaled countries within their regions

region_map = {
    'R10AFRICA':'SSA',
    'R10CHINA+':'CHA',
    'R10EUROPE':'EUR',
    'R10LATIN_AM':'LAM',
    'R10MIDDLE_EAST':'MEA',
    'R10REF_ECON':'REF',
    'R10REST_ASIA':'OAS',
    'R10NORTH_AM':'USA',
    'R10PAC_OECD':'JPN',
    'R10INDIA+':'IND',
    'R10ROWO':'ROWO',
    'World':'World'}


def create_macro_df(idf: pyam.IamDataFrame):
    """Converts data at country level to macro-region data"""

    # Dataset preparation
    df_country = idf.timeseries()
    df_country.index.names = ['model', 'scenario', 'country', 'variable', 'unit']
    
    # Label each country based on what region it's part of
    df_country = df_country.pix.semijoin(REMIND_RMAP.index, how="left")

    # Kick out countries which don't have a region mapping               
    df_country=df_country.loc[~isin(region=np.nan)]
    
    # # Groupby regions and sum (much faster than doing in pyam)
    df_country = pyam.IamDataFrame(
        df_country
        .groupby(['model','scenario','variable','unit','region'])
        .sum())
    
    df_region = pyam.IamDataFrame(df_country)
       
    # Drop 2023 data as it is currently missing quite a few countries (and so the regional totals are off)
    df_region.filter(year=2023,keep=False,inplace=True)

    # Rename regions
    df_region = (df_region
                 .rename(region=region_map)
                 .filter(region=['SSA','CHA','NEU','CAZ','EUR','IND','LAM','MEA','USA','JPN','REF','OAS'])
                )

    # Add world data
    for var in df_region.variable:
        df_region.aggregate_region(
            var,
            'World',
            append=True)

    return df_region

In [54]:
raw_remind = pyam.IamDataFrame(DSCALE_PATH / "data/REMIND_data/REMIND_harm_correctionBio.csv")

pyam.core - INFO: Reading file /Users/marie-charlottegeffray/Library/CloudStorage/Box-Box/Climate Policy Team/02 - Projects/IKEA NDC 1.5° Pathways 23-25 - phase II/2 - Work Packages/WP2 - National 1.5°C Pathways/Downscaling/DSCALE/data/REMIND_data/REMIND_harm_correctionBio.csv

In [134]:
macro_dscale = create_macro_df(dscale_results)

In [145]:
reg_check = subtract(
    raw_remind.timeseries(), 
    macro_dscale.timeseries()
    ).dropna(how="all")

In [251]:
reg_check=reg_check.loc[~isin(region = ["JPN", "USA", "IND", "World"])].loc[~ismatch(variable = ["Price**", "Capaci**", "Trade**", "Revenu**", "Carbon**"])]
reg_check=reg_check.droplevel("unnamed: 0")

In [ ]:
reg_check=reg_check.drop([2005,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019], axis=1)
reg_check=reg_check.dropna(axis=1)

In [301]:
abs_reg_check = reg_check.abs()

In [325]:
mask = (reg_check < -1 ).sum(axis=1)
mask=mask.loc[mask>0]
len(mask)

45

In [326]:
reg_check.loc[mask.index].index.unique("variable")

Index(['Emissions|CO2', 'Primary Energy|Fossil|w/o CCS',
       'Final Energy|Transportation|Liquids|Oil', 'Primary Energy',
       'Primary Energy|Coal', 'Primary Energy|Coal|w/o CCS',
       'Primary Energy|Fossil', 'Primary Energy|Gas',
       'Primary Energy|Gas|w/o CCS', 'Primary Energy|Geothermal',
       'Primary Energy|Oil', 'Primary Energy|Oil|w/o CCS',
       'Primary Energy|Solar', 'Primary Energy|Wind',
       'Secondary Energy|Electricity', 'Secondary Energy|Electricity|Coal',
       'Secondary Energy|Electricity|Solar',
       'Secondary Energy|Electricity|Wind', 'Emissions|CO2|Energy',
       'Emissions|CO2|Industrial Processes',
       'Final Energy|Transportation|Liquids|Coal'],
      dtype='object', name='variable')

In [332]:
reg_check.loc[mask.index].index.unique("region")

Index(['CAZ', 'CHA', 'EUR', 'LAM', 'MEA', 'NEU', 'OAS', 'REF', 'SSA'], dtype='object', name='region')

In [315]:
ts_macro = macro_dscale.timeseries()
ts_raw = raw_remind.timeseries().droplevel("unnamed: 0")

for i in mask.index:
    fig, ax = plt.subplots()

    ts_macro.loc[[i]].T.plot(ax=ax, label = "DSCALE reaggregated")
    ts_raw.loc[[i]].T.plot(ax=ax, label = "Raw REMIND")
    ax.legend(["DSCALE reaggregated", "Raw REMIND"])


    fname = f"{i[2]}_{i[3].replace('/', '_')}.png"
    plt.savefig(f"data_checks/data_checks_neg/{fname}")
    plt.close(fig)

In [328]:
mask = (reg_check > 1 ).sum(axis=1)
mask=mask.loc[mask>0]
len(mask)

60

In [329]:
reg_check.loc[mask.index].index.unique("variable")

Index(['Emissions|CO2', 'Emissions|CO2|Energy',
       'Emissions|CO2|Industrial Processes', 'Primary Energy|Fossil|w/o CCS',
       'Secondary Energy|Electricity', 'Secondary Energy|Hydrogen',
       'Primary Energy|Gas', 'Primary Energy|Gas|w/o CCS',
       'Primary Energy|Nuclear', 'Primary Energy', 'Primary Energy|Solar',
       'Secondary Energy|Electricity|Solar', 'Primary Energy|Fossil',
       'Final Energy|Heat', 'Secondary Energy|Heat'],
      dtype='object', name='variable')

In [331]:
reg_check.loc[mask.index].index.unique("region")

Index(['CAZ', 'CHA', 'EUR', 'LAM', 'MEA', 'NEU', 'OAS', 'REF', 'SSA'], dtype='object', name='region')

In [317]:
ts_macro = macro_dscale.timeseries()
ts_raw = raw_remind.timeseries().droplevel("unnamed: 0")

for i in mask.index:
    fig, ax = plt.subplots()

    ts_macro.loc[[i]].T.plot(ax=ax, label = "DSCALE reaggregated")
    ts_raw.loc[[i]].T.plot(ax=ax, label = "Raw REMIND")
    ax.legend(["DSCALE reaggregated", "Raw REMIND"])


    fname = f"{i[2]}_{i[3].replace('/', '_')}.png"
    plt.savefig(f"data_checks/data_checks_pos/{fname}")
    plt.close(fig)

# Harmonisation checks

In [13]:
dscale_results

<class 'pyam.core.IamDataFrame'>
Index:
 * model    : REMIND-MAgPIE 3.3-4.8 (1)
 * scenario : NPE-convEarly, NPE-convLate, NPE-core, NPE-demandStandard (4)
Timeseries data coordinates:
   region   : ABW, AFG, AGO, ALB, ARE, ARG, ARM, ASM, ATG, AUS, ... ZWE (218)
   variable : Capacity Additions|Electricity|Biomass, ... (491)
   unit     : %, EJ/yr, GW, GW/yr, GWh/yr, Index (2020 = 1), ... million vehicles (22)
   year     : 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, ... 2100 (19)
Meta indicators:
   exclude (bool) False (1)

In [24]:
base_year = 2020
harm_dict_not_equal = dict()
harm_dict_almost_equal = dict()
for variable in dscale_results.filter(variable = ["Capacity*", "Final*"], keep=False).variable:
    agg = (dscale_results.filter(variable = variable, year = base_year).timeseries().groupby(["model", "region", "variable", "unit"]).sum()/4).round(2)
    core = dscale_results.filter(variable = variable, scenario = "NPE-core", year = base_year).timeseries().droplevel(["scenario"]).round(2)
    try:
        mask_equal = (agg != core)
        if len(mask_equal.loc[mask_equal[base_year]==True].index.unique("region")) > 0: 
            harm_dict_not_equal[variable] = mask_equal.loc[mask_equal[base_year]==True].index.unique("region")

        mask_almost = abs(agg - core) > 1
        if len(mask_almost.loc[mask_almost[base_year]==True].index.unique("region")) > 0:
            harm_dict_almost_equal[variable] = mask_almost.loc[mask_almost[base_year]==True].index.unique("region") 
    except: 
        print(variable)

Statistical Difference|Primary Energy
Statistical Difference|Primary Energy|Coal
Statistical Difference|Primary Energy|Fossil
Statistical Difference|Primary Energy|Fossil|w/o CCS
Statistical Difference|Primary Energy|Gas

In [34]:
list(harm_dict_not_equal.keys())

['Carbon Sequestration|CCS',
 'Carbon Sequestration|CCS|Fossil',
 'Emissions|CO2',
 'Emissions|CO2|Energy',
 'Emissions|CO2|Energy|Demand|Industry',
 'Emissions|CO2|Energy|Demand|Residential and Commercial',
 'Emissions|CO2|Energy|Demand|Transportation',
 'Emissions|CO2|Energy|Supply|Electricity',
 'Emissions|Kyoto Gases (incl. indirect AFOLU)',
 'GDP|PPP',
 'Price|Final Energy|Industry|Electricity',
 'Price|Final Energy|Industry|Gases',
 'Price|Final Energy|Industry|Gases|Bioenergy',
 'Price|Final Energy|Industry|Gases|Fossil',
 'Price|Final Energy|Industry|Hydrogen',
 'Price|Final Energy|Industry|Liquids',
 'Price|Final Energy|Industry|Liquids|Bioenergy',
 'Price|Final Energy|Industry|Liquids|Fossil synfuel',
 'Price|Final Energy|Industry|Solids|Biomass',
 'Price|Final Energy|Industry|Solids|Coal',
 'Price|Final Energy|Residential and Commercial|Residential|Electricity',
 'Price|Final Energy|Residential and Commercial|Residential|Gases|Natural Gas',
 'Price|Final Energy|Residential and Commercial|Residential|Liquids|Biomass',
 'Price|Final Energy|Residential and Commercial|Residential|Liquids|Oil',
 'Price|Final Energy|Residential and Commercial|Residential|Solids|Biomass',
 'Price|Final Energy|Residential and Commercial|Residential|Solids|Coal',
 'Price|Final Energy|Transportation|Electricity',
 'Price|Final Energy|Transportation|Gases',
 'Price|Final Energy|Transportation|Hydrogen',
 'Price|Final Energy|Transportation|Liquids',
 'Price|Final Energy|Transportation|Liquids|Fossil synfuel',
 'Price|Primary Energy|Coal',
 'Price|Primary Energy|Gas',
 'Price|Primary Energy|Oil',
 'Price|Secondary Energy|Electricity',
 'Price|Secondary Energy|Gases|Natural Gas',
 'Price|Secondary Energy|Hydrogen',
 'Price|Secondary Energy|Liquids',
 'Price|Secondary Energy|Liquids|Biomass',
 'Price|Secondary Energy|Liquids|Oil',
 'Price|Secondary Energy|Solids|Coal',
 'Primary Energy',
 'Primary Energy|Biomass',
 'Primary Energy|Coal|w/ CCS',
 'Primary Energy|Fossil',
 'Primary Energy|Fossil|w/ CCS',
 'Primary Energy|Fossil|w/o CCS',
 'Primary Energy|Gas',
 'Primary Energy|Gas|w/o CCS',
 'Primary Energy|Nuclear',
 'Primary Energy|Oil',
 'Primary Energy|Oil|w/o CCS',
 'Primary Energy|Wind',
 'Revenue|Government|Tax|Carbon',
 'Revenue|Government|Tax|Carbon|Demand|Industry',
 'Revenue|Government|Tax|Carbon|Demand|Residential and Commercial',
 'Revenue|Government|Tax|Carbon|Demand|Transportation',
 'Revenue|Government|Tax|Carbon|Supply',
 'Secondary Energy|Electricity',
 'Secondary Energy|Electricity|Nuclear',
 'Secondary Energy|Electricity|Trade',
 'Secondary Energy|Electricity|Wind',
 'Secondary Energy|Gases',
 'Secondary Energy|Gases|Biomass',
 'Secondary Energy|Gases|Natural Gas',
 'Secondary Energy|Liquids',
 'Secondary Energy|Liquids|Biomass',
 'Secondary Energy|Liquids|Oil',
 'Secondary Energy|Solids',
 'Secondary Energy|Solids|Biomass',
 'Secondary Energy|Solids|Coal',
 'Statistical Difference|Emissions|CO2|Energy',
 'Statistical Difference|Emissions|CO2|Industrial Processes',
 'Statistical Difference|Emissions|Total Non-CO2',
 'Statistical Difference|Primary Energy|Fossil|w/ CCS',
 'Statistical Difference|Secondary Energy|Electricity',
 'Statistical Difference|Emissions|CO2|LULUCF Direct+Indirect',
 'Statistical Difference|Primary Energy|Biomass',
 'Statistical Difference|Primary Energy|Gas|w/o CCS',
 'Statistical Difference|Primary Energy|Hydro',
 'Statistical Difference|Primary Energy|Oil',
 'Statistical Difference|Primary Energy|Oil|w/o CCS',
 'Statistical Difference|Primary Energy|Solar',
 'Statistical Difference|Secondary Energy|Electricity|Gas',
 'Statistical Difference|Secondary Energy|Electricity|Hydro',
 'Statistical Difference|Secondary Energy|Electricity|Oil',
 'Statistical Difference|Secondary Energy|Electricity|Solar',
 'Statistical Difference|Primary Energy|Coal|w/o CCS',
 'Statistical Difference|Primary Energy|Wind',
 'Statistical Difference|Secondary Energy|Electricity|Coal',
 'Statistical Difference|Secondary Energy|Electricity|Wind',
 'Statistical Difference|Primary Energy|Nuclear',
 'Statistical Difference|Secondary Energy|Electricity|Biomass',
 'Statistical Difference|Secondary Energy|Electricity|Nuclear',
 'Statistical Difference|Primary Energy|Geothermal',
 'Statistical Difference|Secondary Energy|Electricity|Geothermal',
 'Capital Cost|Electricity|Solar|CSP',
 'Capital Cost|Electricity|Solar|PV',
 'Capital Cost|Electricity|Wind|Offshore',
 'Capital Cost|Electricity|Wind|Onshore',
 'Carbon Sequestration|CCS|Fossil|Energy|Supply|Electricity',
 'Carbon Sequestration|CCS|Fossil|Energy|Supply|Hydrogen',
 'Consumption',
 'Energy Service|Transportation|Freight',
 'Energy Service|Transportation|Freight|International Shipping',
 'Energy Service|Transportation|Freight|Navigation',
 'Energy Service|Transportation|Freight|Railways',
 'Energy Service|Transportation|Freight|Road',
 'Energy Service|Transportation|Passenger',
 'Energy Service|Transportation|Passenger|Aviation',
 'Energy Service|Transportation|Passenger|Bicycling and Walking',
 'Energy Service|Transportation|Passenger|Railways',
 'Energy Service|Transportation|Passenger|Road',
 'Energy Service|Transportation|Passenger|Road|Bus',
 'Energy Service|Transportation|Passenger|Road|LDV',
 'GDP|MER',
 'Investment',
 'Investment|Energy Supply',
 'Investment|Energy Supply|Electricity',
 'Investment|Energy Supply|Electricity|Coal',
 'Investment|Energy Supply|Electricity|Coal|w/ CCS',
 'Investment|Energy Supply|Electricity|Coal|w/o CCS',
 'Investment|Energy Supply|Electricity|Electricity Storage',
 'Investment|Energy Supply|Electricity|Fossil',
 'Investment|Energy Supply|Electricity|Gas',
 'Investment|Energy Supply|Electricity|Gas|w/o CCS',
 'Investment|Energy Supply|Electricity|Geothermal',
 'Investment|Energy Supply|Electricity|Hydro',
 'Investment|Energy Supply|Electricity|Non-Biomass Renewables',
 'Investment|Energy Supply|Electricity|Non-fossil',
 'Investment|Energy Supply|Electricity|Nuclear',
 'Investment|Energy Supply|Electricity|Solar',
 'Investment|Energy Supply|Electricity|Wind',
 'Investment|Energy Supply|Heat',
 'Investment|Energy Supply|Hydrogen',
 'Investment|Energy Supply|Hydrogen|Other',
 'Investment|Energy Supply|Liquids',
 'Investment|Energy Supply|Liquids|Biomass',
 'Investment|Energy Supply|Liquids|Oil',
 'Investment|Energy Supply|Other',
 'Primary Energy|Biomass|1st Generation',
 'Primary Energy|Biomass|Heat',
 'Primary Energy|Biomass|Liquids',
 'Primary Energy|Biomass|Modern',
 'Primary Energy|Biomass|Residues',
 'Primary Energy|Biomass|Solids',
 'Primary Energy|Coal|Electricity',
 'Primary Energy|Coal|Electricity|w/o CCS',
 'Primary Energy|Coal|Heat',
 'Primary Energy|Gas|Electricity|w/o CCS',
 'Primary Energy|Gas|Gases',
 'Primary Energy|Gas|Heat',
 'Primary Energy|Gas|Hydrogen',
 'Primary Energy|Non-Biomass Renewables',
 'Production|Cement',
 'Secondary Energy',
 'Secondary Energy|Electricity|Coal|w/o CCS',
 'Secondary Energy|Electricity|Non-Biomass Renewables',
 'Secondary Energy|Electricity|Solar|PV',
 'Secondary Energy|Electricity|Wind|Onshore',
 'Secondary Energy|Heat|Biomass',
 'Secondary Energy|Heat|Coal',
 'Secondary Energy|Liquids|Biomass|w/o CCS',
 'Statistical Difference|Emissions|CO2',
 'Trade|Primary Energy|Oil|Volume',
 'Transport|Stock|Road|Passenger|LDV']

In [40]:
dscale_results.filter(variable = "Emissions*Elec*")

<class 'pyam.core.IamDataFrame'>
Index:
 * model    : REMIND-MAgPIE 3.3-4.8 (1)
 * scenario : NPE-convEarly, NPE-convLate, NPE-core, NPE-demandStandard (4)
Timeseries data coordinates:
   region   : ABW, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, AZE, ... ZWE (193)
   variable : Emissions|CO2|Energy|Supply|Electricity (1)
   unit     : Mt CO2/yr (1)
   year     : 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, ... 2100 (19)
Meta indicators:
   exclude (bool) False (1)

In [38]:
variable = "Emissions|CO2|Energy"
dscale_results.filter(variable = variable, year = [2020], region = harm_dict_not_equal[variable]).timeseries().round(2).unstack("scenario")

                                                                     2020  \
scenario                                                    NPE-convEarly
model                 region variable             unit
REMIND-MAgPIE 3.3-4.8 ESH    Emissions|CO2|Energy Mt CO2/yr          0.32
                      NCL    Emissions|CO2|Energy Mt CO2/yr          0.19
                      PRI    Emissions|CO2|Energy Mt CO2/yr          0.69

                                                                          \
scenario                                                    NPE-convLate
model                 region variable             unit
REMIND-MAgPIE 3.3-4.8 ESH    Emissions|CO2|Energy Mt CO2/yr         0.32
                      NCL    Emissions|CO2|Energy Mt CO2/yr         0.19
                      PRI    Emissions|CO2|Energy Mt CO2/yr         0.69

                                                                      \
scenario                                                    NPE-core
model                 region variable             unit
REMIND-MAgPIE 3.3-4.8 ESH    Emissions|CO2|Energy Mt CO2/yr     0.30
                      NCL    Emissions|CO2|Energy Mt CO2/yr     0.18
                      PRI    Emissions|CO2|Energy Mt CO2/yr     0.69


scenario                                                    NPE-demandStandard
model                 region variable             unit
REMIND-MAgPIE 3.3-4.8 ESH    Emissions|CO2|Energy Mt CO2/yr               0.30
                      NCL    Emissions|CO2|Energy Mt CO2/yr               0.19
                      PRI    Emissions|CO2|Energy Mt CO2/yr               0.55

# Other checks

In [23]:
testing=pyam.IamDataFrame('/Users/marie-charlottegeffray/Documents/Repos/projects/DSCALE/results/5_Explorer_and_New_Variables/REMIND-MAgPIE 3.3-4.8_REMIND_2025_for_testing_2026_01_07_2022_harmo_step5e_Scenario_Explorer_upload_FINAL.xlsx')

pyam.core - INFO: Reading file /Users/marie-charlottegeffray/Documents/Repos/projects/DSCALE/results/5_Explorer_and_New_Variables/REMIND-MAgPIE 3.3-4.8_REMIND_2025_for_testing_2026_01_07_2022_harmo_step5e_Scenario_Explorer_upload_FINAL.xlsx
pyam.core - INFO: No scenarios found in sheet meta

In [11]:
testing.filter(variable = "*Emissions**", region = "DEU").variable

['Emissions|CO2',
 'Emissions|CO2|Energy',
 'Emissions|CO2|Energy|Demand|Industry',
 'Emissions|CO2|Energy|Demand|Residential and Commercial',
 'Emissions|CO2|Energy|Demand|Transportation',
 'Emissions|CO2|Energy|Supply|Electricity',
 'Emissions|CO2|Industrial Processes',
 'Emissions|CO2|LULUCF Direct+Indirect',
 'Emissions|CO2|LULUCF Indirect',
 'Emissions|Kyoto Gases (incl. indirect AFOLU)',
 'Emissions|Total Non-CO2',
 'Statistical Difference|Emissions|CO2|Energy',
 'Statistical Difference|Emissions|CO2|Industrial Processes',
 'Statistical Difference|Emissions|CO2|LULUCF Direct+Indirect',
 'Statistical Difference|Emissions|Total Non-CO2']

In [24]:
testing.filter(variable = "Emissions|CO2|Energy|Supply|Electricity", region = "DEU").timeseries()

                                                                                                                    2010  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  388.8117
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  387.4915
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  387.4833
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  387.5813

                                                                                                                    2015  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  398.4608
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  400.4614
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  388.3576
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  400.6210

                                                                                                                    2020  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  292.5832
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  294.1086
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  284.5811
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  293.5290

                                                                                                                    2022  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  292.5832
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  294.1086
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  284.5811
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  293.5290

                                                                                                                    2025  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  118.0349
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  118.5936
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  116.4393
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  115.6887

                                                                                                                  2030  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  9.7761
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  9.3992
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  9.8085
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  9.1159

                                                                                                                  2035  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  2.2002
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  2.1184
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  2.1253
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  2.7298

                                                                                                                  2040  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.7802
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.7856
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.7787
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  1.0643

                                                                                                                  2045  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.2414
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0000
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr -2.2021
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  7.6927

                                                                                                                  2050  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0239
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0176
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0405
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0514

                                                                                                                  2055  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0061
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0062
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0058
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0154

                                                                                                                  2060  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0078
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0047
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0061
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0189

                                                                                                                  2065  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0051
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0036
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0040
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0146

                                                                                                                  2070  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0014
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0009
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0009
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0013

                                                                                                                  2075  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0017
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0010
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0011
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0016

                                                                                                                  2080  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0020
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0012
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0013
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0019

                                                                                                                  2085  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0020
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0010
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0011
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0017

                                                                                                                  2090  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0020
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0008
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0010
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0014

                                                                                                                  2095  \
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0014
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0006
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0007
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0010

                                                                                                                  2100
model                              scenario           region variable                                unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0007
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0004
                                   NPE-core           DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0004
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Supply|Electricity Mt CO2/yr  0.0004

In [22]:
testing.filter(variable = "Emissions|CO2|Energy|Demand|Transportation", region = "DEU").timeseries()

                                                                                                                       2010  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  196.5815
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  195.8774
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  195.8748
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  195.9512

                                                                                                                       2015  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  194.5908
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  195.8334
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  201.6224
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  196.6494

                                                                                                                       2020  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  166.4971
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  167.4208
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  181.5633
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  167.5569

                                                                                                                       2022  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  166.4971
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  167.4208
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  181.5633
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  167.5569

                                                                                                                       2025  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  120.2339
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  118.3290
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  126.0025
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  121.3149

                                                                                                                      2030  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  84.1674
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  80.5069
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  80.2218
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  76.5989

                                                                                                                      2035  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  51.4690
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  46.8050
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  47.9553
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  42.6091

                                                                                                                      2040  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  21.9635
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  17.0537
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  19.0782
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  16.2455

                                                                                                                     2045  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  3.7762
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  0.1087
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  0.2200
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr  2.0229

                                                                                                                   2050  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2055  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2060  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2065  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2070  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2075  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2080  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2085  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2090  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2095  \
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0

                                                                                                                   2100
model                              scenario           region variable                                   unit
Downscaling[REMIND-MAgPIE 3.3-4.8] NPE-convEarly      DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-convLate       DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-core           DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0
                                   NPE-demandStandard DEU    Emissions|CO2|Energy|Demand|Transportation Mt CO2/yr   0.0